// YDevSphere-v0.2frontend/src/components/GitStatusBadge.tsx
import type { GitStatus } from '../types'

export default function GitStatusBadge({ status }: { status: GitStatus }) {
  if (status.type === 'clean') {
    return (
      <span className="flex items-center gap-1.5 text-[12px] text-[#16A34A]">
        <span className="w-[6px] h-[6px] rounded-full bg-[#16A34A] flex-shrink-0" />
        Clean
      </span>
    )
  }

  if (status.type === 'dirty') {
    return (
      <span className="flex items-center gap-1.5 text-[12px] text-[#D97706]">
        <span className="w-[6px] h-[6px] rounded-full bg-[#D97706] flex-shrink-0" />
        {status.changes} changed
      </span>
    )
  }

  if (status.type === 'detached') {
    return (
      <span className="flex items-center gap-1.5 text-[12px] text-[#DC2626]">
        <span className="w-[6px] h-[6px] rounded-full bg-[#DC2626] flex-shrink-0" />
        Detached
      </span>
    )
  }

  return <span className="text-[12px] text-[#9CA3AF]">— No Git</span>
}

// src/components/GitStatusBadge.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import type { GitStatusView } from "@/types/view";

const props = defineProps<{
  status: GitStatusView;
  /** dirty 时的变更文件数（可选） */
  changes?: number;
}>();

const { t } = useI18n();

interface Style {
  dot: string;
  text: string;
  label: string;
}

const style = computed<Style>(() => {
  switch (props.status) {
    case "clean":
      return { dot: "#16A34A", text: "#16A34A", label: t("git.clean") };
    case "dirty":
      return {
        dot: "#D97706",
        text: "#D97706",
        label: `${props.changes ?? 0} ${t("git.changed")}`,
      };
    case "detached":
      return { dot: "#DC2626", text: "#DC2626", label: t("git.detached") };
    default:
      return { dot: "#9CA3AF", text: "#9CA3AF", label: "—" };
  }
});
</script>

<template>
  <span
    v-if="status === 'none'"
    class="text-[12px] text-[#9CA3AF]"
  >
    —
  </span>
  <span
    v-else
    class="flex items-center gap-1.5 text-[12px]"
    :style="{ color: style.text }"
  >
    <span
      class="h-[6px] w-[6px] shrink-0 rounded-full"
      :style="{ backgroundColor: style.dot }"
    />
    {{ style.label }}
  </span>
</template>
